#:schema node_modules/wrangler/config-schema.json
# name = "todo-list-app"
name = "remix-actorkit-todo"
main = "dist/index.js"
compatibility_date = "2024-09-25"

legacy_assets = "public"

[define]
"process.env.REMIX_DEV_ORIGIN" = "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"
"process.env.ACTOR_KIT_HOST" = "'127.0.0.1:8787'"
"process.env.ACTOR_KIT_SECRET" = "'foobarbaz'"

[vars]
ACTOR_KIT_HOST = "127.0.0.1:8787"
ACTOR_KIT_SECRET = "foobarbaz"
DEBUG_LEVEL = "3"

[[durable_objects.bindings]]
name = "REMIX"
class_name = "Remix"

[[durable_objects.bindings]]
name = "TODO"
class_name = "Todo"

[[migrations]]
tag = "v1"
new_classes = ["Remix"]
