import { getUserId } from "@/session";
import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./user-context";

export const metadata: Metadata = {
  title: "Nextjs ActorKit Todo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await getUserId();
  return (
    <html lang="en">
      <UserProvider userId={userId}>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}
